### ISSUE TITLE
`pawse` triggers in identifiers and strings

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dogescript/dogescript#161]
In the doge3 parser, I have this line:
`very pawseStart is content.content dose startsWith with 'pawse'`

This doesn't work with the code on master, since it gets turned into this:
`var debugger;Start = content.content.startsWith('debugger;');`

**Comment by AnEmortalKid** [comment]
I assume this also happens with the other replacement words, `dogeument` and `windoge` ?

**Comment by vpzomtrrfrt** [comment]
Ah, yes, it does

**Comment by AnEmortalKid** [comment]
ok! i'll try to split handlers for those. those might be tough because we'll have old consumers that might have `dogeument.findElement`. I guess we can make the logic check if it's `dogeument` or if it contains `dogeument.`, same with `windoge`. `pawse` should be able to be handled without contains though!
