### ISSUE TITLE
`amaze` keyword not translated

### ISSUE THREAD

**Issue by eahenle** [dogescript/dogescript#265]
`amaze` is not translated in the example provided in the language definition.

The example:
`much foo
amaze 'bar'
wow`

The result that should be obtained according to the documentation:
`function foo () {
return 'bar';
}`

The actual result:
`function foo () {
amaze 'bar'
}`

Result obtained with Dogescript 2.3.0 as installed via npm, running on Ubuntu 20.04 (Windows Subsystem Linux).

**Comment by AnEmortalKid** [comment]
Ah, i'll double check if this is also broken in master. It might just be broken for anonymous functions, since things with `such` seem to work: https://github.com/dogescript/dogescript/tree/master/test/language-spec/amaze/single-expression

We're getting close to 2.4.0 and @Pholey was double checking what else was needed for that release!

**Comment by AnEmortalKid** [comment]
Ah @eahenle , I believe the doc uses `such` which is for named functions:

```
such foo
amaze 'bar'
wow
```

I think the way things are, you might have to declare things with that level of spacing, I tried a quick fix to support all of it in a single line but there's some mishandled parser state. We sort of expected 2.4.0 to be kinda clunky, but we want to re-write most things from scratch for the 3.x.
